CREATE DATABASE SQL_PROJECT_3
USE SQL_PROJECT_3
SELECT * FROM [dbo].[Customer]
SELECT * FROM [dbo].[prod_cat_info]
SELECT * FROM [dbo].[Transactions]
---1.	Which channel is most frequently used for transactions?
SELECT Store_type 
        FROM
      (SELECT  Store_type,COUNT( Store_type)AS NO_OF_Transactions,
	  DENSE_RANK () OVER (ORDER BY COUNT( Store_type) DESC) AS RANK_OF_Store_type
        FROM Transactions
         GROUP BY  Store_type
          ) T
		  WHERE RANK_OF_Store_type ='1'
----2.	What is the count of Male and Female customers in the database?		
			SELECT GENDER,
				SUM(CASE 
				WHEN GENDER= 'M' THEN 1
				WHEN GENDER ='F' THEN 1
				ELSE 0
				END) AS COUNT_GENDER 
				FROM Customer
				WHERE GENDER IS NOT NULL
               GROUP BY Gender
			  
----3.	From which city do we have the maximum number of customers and how many?				
				SELECT  TOP 1 
				city_code,COUNT(city_code) AS maximum_number_of_customers
				FROM Customer
				WHERE city_code IS NOT NULL
				GROUP BY city_code
				ORDER BY COUNT(city_code) DESC
---4.	How many sub-categories are there under the Books category?
            SELECT prod_cat,COUNT(prod_subcat)AS No_of_prod_subcat
			FROM prod_cat_info
			WHERE prod_cat = 'BOOKS'
			GROUP BY prod_cat
---5.	What is the maximum quantity of products ever ordered?			
					SELECT COUNT (transaction_id) AS NO_OF_transactions,MAX(Qty) AS maximum_quantity_of_products
				FROM Transactions
				
---6.	What is the net total revenue generated in categories Electronics and Books?

	SELECT ((SELECT SUM(total_amt) AS Total_OF_categories_Values
					FROM prod_cat_info AS PR
					 JOIN Transactions AS TR 
					 ON PR.prod_cat_code = TR.prod_cat_code
					 WHERE prod_cat ='Books'
					 GROUP BY prod_cat)
					 +
					 (SELECT SUM(total_amt) AS Total_OF_categories_Values
					FROM prod_cat_info AS PR
					 JOIN Transactions AS TR 
					 ON PR.prod_cat_code = TR.prod_cat_code
					 WHERE prod_cat ='Electronics'
					 GROUP BY prod_cat)) AS Total_revenue
---7.	How many customers have >10 transactions with us, excluding returns?
   WITH Count_of_customers AS
					(SELECT customer_Id, COUNT(transaction_id) Count_of_Transactions,
					SUM(CASE 
					WHEN Qty>0 THEN 1
					ELSE 0
					END) AS GOOD
					FROM Customer AS CU
					JOIN 
					Transactions AS TR
					ON CU.customer_Id = TR.cust_id
					GROUP BY customer_Id 
					HAVING COUNT(transaction_id) >10)
					SELECT COUNT(customer_Id) AS Count_of_customers
					FROM Count_of_customers 
					WHERE customer_Id = GOOD
----8.	What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
      SELECT(               (  SELECT SUM(total_amt) AS Total_Sales
					   FROM Transactions AS TR
					   JOIN prod_cat_info AS PR
					   ON TR.prod_cat_code = PR.prod_cat_code
					   WHERE prod_cat='Electronics' AND Store_type='Flagship store'
					   )
					   +
					    (SELECT SUM(total_amt) AS Total_Sales
					   FROM Transactions AS TR
					   JOIN prod_cat_info AS PR
					   ON TR.prod_cat_code = PR.prod_cat_code
					   WHERE prod_cat='Clothing' AND Store_type='Flagship store'
					  )) AS combined_revenue
---9.	What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
									WITH  Total_revenue_by_prod_sub_cat AS 
									       (SELECT  Gender,
										   SUM(total_amt) AS total_revenue,
										   prod_cat,prod_subcat
											FROM  Transactions AS TR
											    JOIN  Customer AS CU
												ON TR.cust_id = CU.customer_Id
												JOIN prod_cat_info AS PR
												ON TR.prod_cat_code = PR.prod_cat_code
												WHERE Gender = 'M' AND prod_cat='Electronics'
											GROUP BY Gender,prod_cat,prod_subcat) 
										SELECT  SUM(total_revenue) AS total_revenue_by_prod_sub_cat
										FROM Total_revenue_by_prod_sub_cat

----10.	What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
		
		WITH sub_categories AS 
				( SELECT prod_subcat  ,

						  	ROUND(   ( SUM(CASE 
						      WHEN total_amt>0 THEN total_amt
							   END )/(SELECT SUM (total_amt) FROM Transactions)*100) ,1)AS percentage_of_sales,

						ABS(	ROUND(   (SUM (CASE
							       WHEN total_amt <0 THEN total_amt
								   END)/(SELECT SUM(total_amt) FROM Transactions)*100) , 1 ) )AS percentage_of_returns

			       FROM Transactions AS TR
					JOIN  prod_cat_info AS PR
						ON TR.prod_subcat_code = PR.prod_sub_cat_code
						  GROUP BY prod_subcat   )
              
			                SELECT TOP 5 *
                            FROM sub_categories
							ORDER BY percentage_of_sales DESC

					
---11.	For all customers aged between 25 to 35 years 
----find what is the net total revenue generated by these consumers in last 30 days 
-----of transactions from max transaction date available in the data?

                       SELECT SUM(total_amt) AS total_revenue,
					  
					   DATEDIFF(YEAR,DOB,GETDATE()) AS Age
					   FROM Customer AS CU
					   JOIN Transactions AS TR
					   ON CU.customer_Id =TR.cust_id
						WHERE DATEDIFF(YEAR,DOB,GETDATE()) BETWEEN 25 AND 35 
						AND TR.tran_date>=(SELECT DATEADD(DAY,-30,MAX(tran_date)) FROM Transactions)
						 GROUP BY DATEDIFF(YEAR,DOB,GETDATE())


--12.Which product category has seen the max value of returns in the last 3 months of transactions?
                      SELECT prod_cat,
					  SUM(CASE 
					  WHEN  Qty<0 THEN 1
					  ELSE 0
					  END) AS count_of_returns
					  FROM Transactions AS TR
					  JOIN prod_cat_info AS PR
					  ON TR.prod_cat_code = PR .prod_cat_code
					  GROUP BY  prod_cat
---13.	Which store-type sells the maximum products; by value of sales amount and by quantity sold?
							SELECT Store_type,
							MAX(CASE 
							WHEN total_amt>0 THEN total_amt
							END)AS Total_Salse_price,
						
							MAX(CASE
							WHEN Qty>0 THEN Qty
							END )AS Total_Product
						     FROM Transactions
							 WHERE Store_type IS NOT NULL
						GROUP BY  Store_type	
                 
-----14.	What are the categories for which average revenue is above the overall average.

				SELECT prod_cat ,
				ROUND(AVG(total_amt),2) AS Cat_W_Avg
				FROM Transactions AS TR
				JOIN prod_cat_info AS PR
				ON TR.prod_cat_code =PR.prod_cat_code 
				GROUP BY prod_cat
				HAVING ROUND(AVG(total_amt),2)> (SELECT AVG(total_amt) FROM Transactions)
----15.	Find the average and total revenue by 
---each subcategory 
---for the categories which are among top 5 categories in terms of quantity sold
       SELECT TOP 5 prod_cat, prod_subcat ,
	   ROUND(SUM(total_amt),2) AS Total_salse,
	   ROUND(AVG(total_amt),2) AS Avg_OF_Total_salse

	   FROM Transactions AS TR
	       JOIN prod_cat_info AS PR
		   ON TR.prod_cat_code = PR.prod_cat_code
			GROUP BY  prod_cat, prod_subcat 
			ORDER BY prod_cat

SELECT * FROM [dbo].[Customer]
SELECT * FROM [dbo].[prod_cat_info]
SELECT * FROM [dbo].[Transactions]




